---
- name: Install dst command-line tool
  pip: name=dst state=latest
  tags: [dst, dst-cli]

- name: Install packages
  apt: pkg={{item}} state=latest
  with_items: dst_apt_packages
  tags: [dst, dst-apt]

- name: numpy - upgrade
  pip: name=numpy state=latest
  tags: [dst, dst-numpy]

- name: matplotlib - install
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items: matplotlib_apt_packages
  tags: [dst, dst-matplotlib]

- name: Install Python packages
  pip: name={{ item }} state=latest
  with_items: dst_pip_packages
  tags: [dst, dst-pip]

- name: Make sure that the repos directory exists
  file: path=/home/{{ dst_user }}/repos state=directory owner={{ dst_user }} group={{ dst_user }}
  tags: [dst, dst-r]

- name: R - add keyserver
  shell: sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
  tags: [dst, dst-r]

- name: R - add repo
  apt_repository: repo='{{ r_repository }}' state=present
  tags: [dst, dst-r]

- name: R - install
  apt: pkg=r-base-dev state=latest update_cache=yes
  tags: [dst, dst-r]

- name: Install R packages
  shell: echo "install.packages(c('{{item}}'),repos='http://cran.us.r-project.org')" | R --slave --no-save --no-restore-history
  with_items: dst_r_packages
  tags: [dst, dst-r]

- name: Download bundles
  git: repo=https://github.com/DataScienceToolbox/data-science-toolbox.git dest=/usr/lib/data-science-toolbox
  tags: [dst, dst-bundles]
